# .goreleaser.yml
project_name: app
builds:
  - id: dtm_amd64
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
    goarch:
      - amd64
    dir: .
    main: main.go
    ldflags:
      - -s -w -X main.Version=v{{.Version}}
  #- id: dtm_arm64
  #  env: [CGO_ENABLED=0]
  #  goos:
  #    - darwin
  #  goarch:
  #    - arm64
  #  dir: .
  #  main: main.go
  #  ldflags:
  #    - -s -w -X main.Version=v{{.Version}}
